version: '2.2'
services:

  test_elasticsearch_integration:
    image: elasticsearch:7.8.0
    container_name: test_elasticsearch_integration
    environment:
      - node.name=test_elasticsearch_integration
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=test_elasticsearch_integration
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - edx_analytics_pipeline_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  edx_analytics_pipeline_data:
    driver: local
