- name: Checkout repositories
  hosts: "{{ name }}"
  gather_facts: True

  vars:
    - working_dir: "{{ root_data_dir }}/{{ uuid }}"
    - log_dir: "{{ root_log_dir }}/{{ uuid}}"

  tasks:
    - name: repositories checked out
      git: >
        repo={{ item.url }}
        dest={{ working_dir }}/{{ item.dir_name }}
        version=master
      with_items: repos

    - name: branches fetched
      command: git fetch --all chdir={{ working_dir }}/{{ item.dir_name }}
      with_items: repos

    - name: origin/HEAD updated
      command: git remote set-head origin --auto chdir={{ working_dir }}/{{ item.dir_name }}
      with_items: repos

    - name: branches checked out
      command: git checkout {{ item.branch }} chdir={{ working_dir }}/{{ item.dir_name }}
      with_items: repos

    - name: logging configured
      template: src=logging.cfg.j2 dest={{ working_repo_dir }}/logging.cfg

    - name: configuration override removed
      file: path={{ working_repo_dir }}/override.cfg state=absent

    - name: configuration override installed
      copy: src={{ override_config }} dest={{ working_repo_dir }}/override.cfg mode=644
      when: override_config is defined

    - name: boto configured
      copy: src=boto.cfg dest={{ working_repo_dir }}/.boto mode=644
